using System.Threading;
using BepInEx;
using HarmonyLib;
using Newtonsoft.Json.Linq;
using ScamWYF.Modding.Core;
using UnityEngine;
using UnityEngine.UIElements;

namespace ExampleMod
{
    /// <summary>
    /// The smallest mod that uses every shared service. Copy this folder, rename the namespace and the
    /// guid, and you have a working mod.
    /// </summary>
    /// <remarks>
    /// Note what is not here: no Awake, no Update, no OnGUI, and no window. ScamMod seals the Unity
    /// callbacks and handles them for you, and the mod menu is built for you - press F1 and this mod has
    /// a tab showing its patches and its settings, drawn in the base game's own UI theme.
    ///
    /// The two things a mod normally has to get right by hand are already done:
    ///
    ///  - patches go through the coordinator, so two mods wanting the same method is reported rather
    ///    than being a mystery;
    ///  - the config is watched, so editing the .cfg in a text editor takes effect without a restart.
    ///
    /// And the version is not typed here. PluginBuildInfo.Version is generated by build.ps1 from your
    /// repository's git tag, so a released dll always reports the tag it was cut from. It is a const
    /// because [BepInPlugin]'s arguments have to be compile-time constants. A hand-written "1.0.0"
    /// is correct on the first release and silently wrong on every release after it - and it is not
    /// only untidy, because this library's Plugins tab and the launcher's Mods tab both read the
    /// version back out of the dll and show it to the player.
    /// </remarks>
    [BepInPlugin(PluginGuid, "Example Mod", PluginBuildInfo.Version)]
    public sealed class Plugin : ScamMod
    {
        public const string PluginGuid = "com.example.scamwyf.examplemod";

        // Unity build this was written against. A mismatch is a warning, not an error.
        private const string BuiltAgainst = "6000.3.10f1";

        private HarmonyMethod _prefix;
        private int _requestsSeen;

        protected override void OnModLoad()
        {
            GameBuild.CheckUnityVersion(ModLog, ModId, BuiltAgainst);

            // Settings gives the in-game editor something to draw: a setting bound with a range becomes
            // a slider, and its description becomes the help text.
            var settings = Settings;
            var greetingLength = settings.Bind("General", "GreetingLength", 24, 1, 200,
                "How long the greeting is. Also the slider on this tab.");

            // Pick up an edit to the .cfg while the game is running.
            WatchConfig();

            _prefix = new HarmonyMethod(AccessTools.Method(typeof(Plugin), nameof(Prefix)));

            if (!PatchCoordinator.TryPatch(
                    this,
                    typeof(KolkataApi),
                    "CompleteOpenRouterAsync",
                    new[] { typeof(JObject), typeof(CancellationToken), typeof(bool) },
                    "count AI requests",
                    _prefix))
            {
                // The method is gone, so the game was updated. Carry on without the patch rather
                // than disabling the whole mod over one feature.
                ModLog.LogWarning("Running without the request counter.");
            }

            ModLog.LogInfo("Greeting length is " + settings.Int(greetingLength, 1, 200) + ".");
        }

        protected override void OnModUnload()
        {
            // Harmony patches, hotkeys, windows and menu tabs are cleaned up by ScamMod. Anything else
            // you started - coroutines, sockets, DontDestroyOnLoad objects - is yours to stop here.
        }

        private static bool Prefix()
        {
            // Return false to skip the original method.
            return true;
        }

        /// <summary>
        /// Replace the tab ScamMod gave this mod with one of your own. Only worth doing when there is
        /// something worth showing; the default tab already lists patches, hotkeys and every setting.
        /// </summary>
        private void RegisterPage()
        {
            ModMenu.AddPage(this, "Example", BuildPage, -10);
        }

        private void BuildPage(VisualElement page)
        {
            var scroll = Widgets.Scroll(page);

            Widgets.FieldRow(scroll, "Requests seen", _requestsSeen.ToString());
            Widgets.Paragraph(scroll, "This tab replaced the default one, so the settings editor is not " +
                                      "shown here. Delete the AddPage call and it comes back.");

            var row = Widgets.WrapRow(scroll);
            Widgets.DescribedButton(row, "Reset counter", "Zero the request count",
                delegate { _requestsSeen = 0; ModMenu.Refresh(); });
        }
    }
}