<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>WatcherTests</AssemblyName>
    <RootNamespace>WatcherTests</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Stubs.cs" />
    <Compile Include="FakeConfigFile.cs" />
    <Compile Include="ConfigWatcher.cs" />
    <Compile Include="WatcherTests.cs" />
  </ItemGroup>
</Project>